# Specify include directory
# This directory must contain symbolic links to DRAMSim and FlashDIMMSim
# TODO: If the .so files for these are not already build, they will be by build.
INCLUDEDIR=/home/jims/include

###################################################


CXXFLAGS= -O0 -DDEBUG_BUILD -DNO_STORAGE -Wall
#CXXFLAGS= -O3 -DNO_OUTPUT -DNO_STORAGE -Wall


ifdef DEBUG
ifeq (${DEBUG}, 0)
CXXFLAGS= -O3 -DNO_STORAGE -DNO_OUTPUT -L
endif
endif
ifdef PROFILE
CXXFLAGS = -pg
endif 

INCLUDES=${INCLUDEDIR}
LIBS=${INCLUDEDIR}/DRAMSim

EXE_NAME=HybridSim
LIB_NAME=libhybridsim.so

SRC = $(wildcard *.cpp)
OBJ = $(addsuffix .o, $(basename $(SRC)))
POBJ = $(addsuffix .po, $(basename $(SRC)))
REBUILDABLES=$(OBJ) ${POBJ} $(EXE_NAME) $(LIB_NAME)

all: ${EXE_NAME} 

#   $@ target name, $^ target deps, $< matched pattern
$(EXE_NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) -L${LIBS} -ldramsim -Wl,-rpath=${LIBS} -o $@ $^ 
	@echo "Built $@ successfully" 

${LIB_NAME}: ${POBJ}
	g++ -g -shared -Wl,-soname,$@ -o $@ $^
	@echo "Built $@ successfully"

#include the autogenerated dependency files for each .o file
-include $(OBJ:.o=.dep)
-include $(POBJ:.po=.dep)

# build dependency list via gcc -M and save to a .dep file
%.dep : %.cpp
	@$(CXX) -I$(INCLUDES) -std=c++0x -M $(CXXFLAGS) $< > $@

# build all .cpp files to .o files
%.o : %.cpp
	g++ $(CXXFLAGS) -I$(INCLUDES) -std=c++0x -o $@ -c $<

MBOBSim.o: TraceBasedSim.cpp
	g++ ${CXXFLAGS} -DMBOB_SYSTEM -o $@ -c $<

%.po : %.cpp
	g++ -I$(INCLUDES) -std=c++0x -O3 -ffast-math -fPIC -DNO_OUTPUT -DNO_STORAGE -o $@ -c $<
clean: 
	rm -f ${REBUILDABLES} *.dep out
