# HybridSim build system

###################################################

CXXFLAGS=-m64 -DNO_STORAGE -Wall -DDEBUG_BUILD -std=c++0x
OPTFLAGS=-m64 -O3


ifdef DEBUG
ifeq ($(DEBUG), 1)
OPTFLAGS= -O0 -g
endif
endif
CXXFLAGS+=$(OPTFLAGS)


DRAM_LIB=../DRAMSim2
NV_LIB=../NVDIMMSim/src
#NV_LIB=../FNVSim

INCLUDES=-I$(DRAM_LIB) -I$(NV_LIB)
LIBS=-L${DRAM_LIB} -L${NV_LIB} -ldramsim -lnvdsim -Wl,-rpath=${DRAM_LIB} -Wl,-rpath=${NV_LIB}

EXE_NAME=HybridSim
LIB_NAME=libhybridsim.so

SRC = $(wildcard *.cpp)
OBJ = $(addsuffix .o, $(basename $(SRC)))
POBJ = $(addsuffix .po, $(basename $(SRC)))
REBUILDABLES=$(OBJ) ${POBJ} $(EXE_NAME) $(LIB_NAME)

all: ${EXE_NAME} 

lib: ${LIB_NAME} 

#   $@ target name, $^ target deps, $< matched pattern
$(EXE_NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ ${LIBS}
	@echo "Built $@ successfully" 

${LIB_NAME}: ${POBJ}
	g++ -g -shared -Wl,-soname,$@ -o $@ $^ ${LIBS}
	@echo "Built $@ successfully"

#include the autogenerated dependency files for each .o file
-include $(OBJ:.o=.dep)
-include $(POBJ:.po=.deppo)

# build dependency list via gcc -M and save to a .dep file
%.dep : %.cpp
	@$(CXX) $(INCLUDES) -std=c++0x -M $(CXXFLAGS) $< > $@
%.deppo : %.cpp
	@$(CXX) $(INCLUDES) -std=c++0x -M $(CXXFLAGS) -MT"$*.po" $< > $@

# build all .cpp files to .o files
%.o : %.cpp
	g++ $(CXXFLAGS) $(INCLUDES) -std=c++0x -o $@ -c $<

%.po : %.cpp
	g++ $(INCLUDES) -std=c++0x -O3 -g -ffast-math -fPIC -DNO_OUTPUT -DNO_STORAGE -o $@ -c $<

clean: 
	rm -rf ${REBUILDABLES} *.dep *.deppo out results *.log callgrind*
