hybridsim: 
	g++ -c ptlcall_hybridsim.cpp
	g++ -c util.cpp
	g++ -o ptlcall_hybridsim ptlcall_hybridsim.o util.o

single_flush:
	g++ -o ptlcall_single_flush ptlcall_single_flush.c

clean:
	rm -rf *.o
	rm ptlcall_single_flush ptlcall_hybridsim
